// ข้อมูลเดิมสำหรับฝั่งผู้ประกันตนและสถิติรวม (สำหรับหน้า Dashboard และ User Profile)
export const claims = [
  { id: "SSO-2025-0045", user: "พชรพล อาจม่วง", type: "Medical Grant (ค่ารักษาพยาบาล)", status: "success", amount: 5800 },
  { id: "SSO-2025-0042", user: "สมชาย ใจดี", type: "Disability Benefit (ทุพพลภาพ)", status: "success", amount: 15000 },
  { id: "SSO-2025-0048", user: "วิชัย มานะยอด", type: "Old-Age Pension (กรณีชราภาพ)", status: "success", amount: 150000 },
];

// ข้อมูลใหม่สำหรับฝั่งเจ้าหน้าที่ (Pending Claims สำหรับการตรวจสอบ)
export const pendingClaims = [
  {
    id: "SSO-REQ-8892",
    user: "ภัทรกฤต สังเคราะห์",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "12 เม.ย. 2569",
    aiConfidence: 98,
    isProxy: false,
    amount: 5800,
    hospital: "โรงพยาบาลศิริราช",
    documentUrl: "/mock-doc-1.jpg",
  },
  {
    id: "SSO-REQ-8893",
    user: "สมชาย ใจดี",
    type: "Disability Benefit (ทุพพลภาพ)",
    date: "12 เม.ย. 2569",
    aiConfidence: 75,
    isProxy: true,
    proxyDetails: { proxyName: "สมหญิง ใจดี (ภรรยา)", consentStatus: "Verified", consentDate: "10 เม.ย. 2569" },
    amount: 15000,
    hospital: "โรงพยาบาลจุฬาลงกรณ์",
    documentUrl: "/mock-doc-2.jpg",
  },
  {
    id: "SSO-REQ-8901",
    user: "วิชัย มานะยอด",
    type: "Old-Age Pension (กรณีชราภาพ)",
    date: "13 เม.ย. 2569",
    aiConfidence: 95,
    isProxy: false,
    amount: 185000,
    hospital: "-",
    documentUrl: "/mock-doc-3.jpg",
  },
  {
    id: "SSO-REQ-8902",
    user: "รุ่งนภา สว่างจิต",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "13 เม.ย. 2569",
    aiConfidence: 92,
    isProxy: false,
    amount: 3200,
    hospital: "โรงพยาบาลรามาธิบดี",
    documentUrl: "/mock-doc-1.jpg",
  },
  {
    id: "SSO-REQ-8903",
    user: "ประเสริฐ คงกระพัน",
    type: "Disability Benefit (ทุพพลภาพ)",
    date: "14 เม.ย. 2569",
    aiConfidence: 82,
    isProxy: true,
    proxyDetails: { proxyName: "มานี คงกระพัน (บุตร)", consentStatus: "Verified", consentDate: "13 เม.ย. 2569" },
    amount: 45000,
    hospital: "โรงพยาบาลธรรมศาสตร์",
    documentUrl: "/mock-doc-2.jpg",
  },
  {
    id: "SSO-REQ-8904",
    user: "จันทร์เพ็ญ สวยงาม",
    type: "Old-Age Pension (กรณีชราภาพ)",
    date: "14 เม.ย. 2569",
    aiConfidence: 99,
    isProxy: true,
    proxyDetails: { proxyName: "สมบัติ สวยงาม (บุตร)", consentStatus: "Verified", consentDate: "14 เม.ย. 2569" },
    amount: 210000,
    hospital: "-",
    documentUrl: "/mock-doc-3.jpg",
  },
  {
    id: "SSO-REQ-8905",
    user: "เกียรติศักดิ์ รักไทย",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "15 เม.ย. 2569",
    aiConfidence: 65,
    isProxy: false,
    amount: 12800,
    hospital: "โรงพยาบาลกรุงเทพ",
    documentUrl: "/mock-doc-1.jpg",
  },
  {
    id: "SSO-REQ-8906",
    user: "บุญส่ง มีมาก",
    type: "Old-Age Pension (กรณีชราภาพ)",
    date: "15 เม.ย. 2569",
    aiConfidence: 97,
    isProxy: false,
    amount: 192000,
    hospital: "-",
    documentUrl: "/mock-doc-3.jpg",
  },
  {
    id: "SSO-REQ-8907",
    user: "อารีรัตน์ ขยันงาน",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "16 เม.ย. 2569",
    aiConfidence: 89,
    isProxy: true,
    proxyDetails: { proxyName: "ธนา ขยันงาน (สามี)", consentStatus: "Verified", consentDate: "15 เม.ย. 2569" },
    amount: 4500,
    hospital: "โรงพยาบาลสมิติเวช",
    documentUrl: "/mock-doc-1.jpg",
  },
  {
    id: "SSO-REQ-8908",
    user: "มานะ อดทน",
    type: "Disability Benefit (ทุพพลภาพ)",
    date: "16 เม.ย. 2569",
    aiConfidence: 72,
    isProxy: false,
    amount: 35000,
    hospital: "โรงพยาบาลนพรัตน์",
    documentUrl: "/mock-doc-2.jpg",
  },
  {
    id: "SSO-REQ-8909",
    user: "พรทิพย์ สดใส",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "17 เม.ย. 2569",
    aiConfidence: 94,
    isProxy: false,
    amount: 2100,
    hospital: "โรงพยาบาลยันฮี",
    documentUrl: "/mock-doc-1.jpg",
  },
  {
    id: "SSO-REQ-8910",
    user: "สุรพล แข็งแรง",
    type: "Old-Age Pension (กรณีชราภาพ)",
    date: "17 เม.ย. 2569",
    aiConfidence: 98,
    isProxy: false,
    amount: 175000,
    hospital: "-",
    documentUrl: "/mock-doc-3.jpg",
  },
  {
    id: "SSO-REQ-8911",
    user: "กนกวรรณ วงศ์ดี",
    type: "Disability Benefit (ทุพพลภาพ)",
    date: "18 เม.ย. 2569",
    aiConfidence: 81,
    isProxy: true,
    proxyDetails: { proxyName: "ปรีชา วงศ์ดี (พี่ชาย)", consentStatus: "Verified", consentDate: "17 เม.ย. 2569" },
    amount: 52000,
    hospital: "โรงพยาบาลพญาไท",
    documentUrl: "/mock-doc-2.jpg",
  },
  {
    id: "SSO-REQ-8912",
    user: "วีระพล ร่ำรวย",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "18 เม.ย. 2569",
    aiConfidence: 91,
    isProxy: false,
    amount: 15600,
    hospital: "โรงพยาบาลวชิระ",
    documentUrl: "/mock-doc-1.jpg",
  },
  {
    id: "SSO-REQ-8913",
    user: "ดวงใจ รักสงบ",
    type: "Old-Age Pension (กรณีชราภาพ)",
    date: "19 เม.ย. 2569",
    aiConfidence: 96,
    isProxy: false,
    amount: 230000,
    hospital: "-",
    documentUrl: "/mock-doc-3.jpg",
  },
  {
    id: "SSO-REQ-8914",
    user: "ไพโรจน์ รุ่งเรือง",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "19 เม.ย. 2569",
    aiConfidence: 85,
    isProxy: true,
    proxyDetails: { proxyName: "สายใจ รุ่งเรือง (ภรรยา)", consentStatus: "Verified", consentDate: "18 เม.ย. 2569" },
    amount: 7800,
    hospital: "โรงพยาบาลสงฆ์",
    documentUrl: "/mock-doc-1.jpg",
  },
  {
    id: "SSO-REQ-8915",
    user: "นรีรัตน์ สวยสม",
    type: "Disability Benefit (ทุพพลภาพ)",
    date: "20 เม.ย. 2569",
    aiConfidence: 78,
    isProxy: false,
    amount: 28000,
    hospital: "โรงพยาบาลรามาธิบดี",
    documentUrl: "/mock-doc-2.jpg",
  },
  {
    id: "SSO-REQ-8916",
    user: "อเนก มีชัย",
    type: "Old-Age Pension (กรณีชราภาพ)",
    date: "20 เม.ย. 2569",
    aiConfidence: 99,
    isProxy: false,
    amount: 145000,
    hospital: "-",
    documentUrl: "/mock-doc-3.jpg",
  },
  {
    id: "SSO-REQ-8917",
    user: "ปิยะพงษ์ ผิวผ่อง",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "21 เม.ย. 2569",
    aiConfidence: 93,
    isProxy: false,
    amount: 4900,
    hospital: "โรงพยาบาลตำรวจ",
    documentUrl: "/mock-doc-1.jpg",
  },
  {
    id: "SSO-REQ-8918",
    user: "อำนาจ พลังงาน",
    type: "Disability Benefit (ทุพพลภาพ)",
    date: "21 เม.ย. 2569",
    aiConfidence: 84,
    isProxy: true,
    proxyDetails: { proxyName: "บารมี พลังงาน (บุตร)", consentStatus: "Verified", consentDate: "20 เม.ย. 2569" },
    amount: 39000,
    hospital: "โรงพยาบาลกลาง",
    documentUrl: "/mock-doc-2.jpg",
  },
  {
    id: "SSO-REQ-8919",
    user: "สายชล วารี",
    type: "Old-Age Pension (กรณีชราภาพ)",
    date: "22 เม.ย. 2569",
    aiConfidence: 97,
    isProxy: false,
    amount: 205000,
    hospital: "-",
    documentUrl: "/mock-doc-3.jpg",
  },
  {
    id: "SSO-REQ-8920",
    user: "กมลชนก ดอกไม้",
    type: "Medical Grant (ค่ารักษาพยาบาล)",
    date: "22 เม.ย. 2569",
    aiConfidence: 90,
    isProxy: false,
    amount: 1200,
    hospital: "โรงพยาบาลพระมงกุฎ",
    documentUrl: "/mock-doc-1.jpg",
  }
];

// ข้อมูลประวัติการดำเนินการ (Activity Logs)
export const activityLogs = [
  {
    id: "LOG-1001",
    claimId: "SSO-REQ-8801",
    user: "วิชัย มานะยอด",
    action: "Approved",
    officer: "ภัทรกฤต สังเคราะห์",
    date: "05 เม.ย. 2569",
    time: "10:30",
    note: "เอกสารครบถ้วน AI ตรวจสอบผ่าน"
  },
  {
    id: "LOG-1002",
    claimId: "SSO-REQ-8805",
    user: "เกียรติศักดิ์ รักไทย",
    action: "Rejected",
    officer: "ภัทรกฤต สังเคราะห์",
    date: "05 เม.ย. 2569",
    time: "14:15",
    note: "ใบรับรองแพทย์ไม่มีตราปั๊มโรงพยาบาล"
  },
  {
    id: "LOG-1003",
    claimId: "SSO-REQ-8810",
    user: "สุรพล แข็งแรง",
    action: "Requested Info",
    officer: "ภัทรกฤต สังเคราะห์",
    date: "06 เม.ย. 2569",
    time: "09:00",
    note: "ขอสำเนาบัตรประชาชนเพิ่มเติม"
  }
];